//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABM_de_Paises
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string Paises { get; set; }
        public string Ciudades { get; set; }
        public string Provincias { get; set; }
    }
}
